name: React + TS CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔍 Debug: show where we are and what files e
      - name: Print workspace tree
        run: |
          pwd
          ls -la
          echo "---- react-app ----"
          ls -la react-app || true

      - name: Install dependencies
        working-directory: ./react-app
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Type check
        working-directory: ./react-app
        run: npx tsc --noEmit

      - name: Build
        working-directory: ./react-app
        run: npm run build

      - name: Upload dist artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: react-app-dist
          path: react-app/dist
